# Generated by Django 3.0.5 on 2022-01-24 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('organization', models.CharField(default=None, max_length=30)),
                ('username', models.EmailField(max_length=60, unique=True, verbose_name='username')),
                ('is_registered', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=360)),
                ('receiver_email', models.EmailField(max_length=60)),
                ('date_created', models.CharField(default='', max_length=100)),
                ('author', models.EmailField(default=None, max_length=60, verbose_name='username')),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('videoID', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=500)),
                ('tagger1', models.IntegerField(default=0)),
                ('tagger2', models.IntegerField(default=0)),
                ('instructor', models.EmailField(default=None, max_length=60, verbose_name='third_user')),
                ('tagger1Complete', models.BooleanField(default=False)),
                ('tagger2Complete', models.BooleanField(default=False)),
                ('author', models.EmailField(default=None, max_length=60, verbose_name='username')),
                ('message', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('thought_choice', models.CharField(choices=[('TH', 'Thought'), ('FE', 'Feeling')], max_length=2)),
                ('tone', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3)),
                ('context', models.CharField(choices=[('SLF', 'Self'), ('DPT', 'Dialogue Partner'), ('OPP', 'Other Person or Persons'), ('CTX', 'Current Context'), ('OEC', 'Other Event or Circumstance')], max_length=3)),
                ('comment', models.CharField(default='', max_length=600)),
                ('timestamp', models.FloatField(default=0, max_length=6)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Videos')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When was this token generated')),
                ('key', models.CharField(db_index=True, max_length=110, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, default='', null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256, verbose_name='HTTP User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='The User which is associated to this password reset token')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=360)),
                ('date_created', models.CharField(default='', max_length=100)),
                ('username', models.EmailField(max_length=60, verbose_name='username')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_author', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_token', models.CharField(db_index=True, max_length=110, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
