# Generated by Django 3.0.5 on 2020-11-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='initialTagger',
            new_name='tagger1',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='secondaryTagger',
            new_name='tagger2',
        ),
    ]
