# Generated by Django 3.0.5 on 2020-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201121_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='taggingComplete',
            new_name='tagger1Complete',
        ),
        migrations.AddField(
            model_name='videos',
            name='tagger2Complete',
            field=models.BooleanField(default=False),
        ),
    ]
